### ISSUE TITLE
Celebi shirt and HGSS clothing missing

### ISSUE THREAD

**Issue by eisnerguy1** [ZeChrales/PogoAssets#19]
I'm not seeing these images at all:
```
f_shirt_celebi_bundle_icon
Celebi Shirt

m_shirt_celebi_bundle_icon
Celebi Shirt

m_hat_hgss_bundle_icon
Johto Cap

m_backpack_hgss_bundle_icon
Johto Bag

m_shirt_hgss_bundle_icon
Johto Top

m_pants_hgss_bundle_icon
Johto Pants

m_shoes_hgss_bundle_icon
Johto Shoes

f_hat_hgss_bundle_icon
Johto Cap

f_backpack_hgss_bundle_icon
Johto Bag

f_shirt_hgss_bundle_icon
Johto Top

f_pants_hgss_bundle_icon
Johto Pants

f_socks_hgss_bundle_icon
Johto Socks

f_shoes_hgss_bundle_icon
Johto Shoes
```
I've checked all the folders and I'm just not seeing these.

**Comment by ryankane** [comment]
Were these t-shirt designs actually [created by owoPlusle](https://www.teepublic.com/user/ou_plusle) or are they imitations of Niantic/Pokemon Company? Because they are exceptional.

<img title="Celebi" alt="Celebi" src="https://user-images.githubusercontent.com/1094151/48637745-a52a8f80-e99c-11e8-9ef3-fca75533826c.jpg" data-canonical-src="https://user-images.githubusercontent.com/1094151/48637745-a52a8f80-e99c-11e8-9ef3-fca75533826c.jpg" width="192" height="192" /><img title="Latios" alt="Latios" src="https://user-images.githubusercontent.com/1094151/48637746-a52a8f80-e99c-11e8-9d6f-843a41930bea.jpg" data-canonical-src="https://user-images.githubusercontent.com/1094151/48637746-a52a8f80-e99c-11e8-9d6f-843a41930bea.jpg" width="192" height="192" /><img title="Mew" alt="Mew" src="https://user-images.githubusercontent.com/1094151/48637747-a52a8f80-e99c-11e8-82ac-0cf7b3d18d21.jpg" data-canonical-src="https://user-images.githubusercontent.com/1094151/48637747-a52a8f80-e99c-11e8-82ac-0cf7b3d18d21.jpg" width="192" height="192" />

**Comment by ZeChrales** [comment]
it should be up to date now
